"""add created_on default function

Revision ID: b8565b025959
Revises: 13afeb198861
Create Date: 2024-05-12 23:43:17.060986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8565b025959'
down_revision: Union[str, None] = '13afeb198861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('posts', 'date_added')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2024-05-12 19:12:36.948471+00'::timestamp with time zone"), autoincrement=False, nullable=True))
    op.drop_column('posts', 'created_on')
    # ### end Alembic commands ###
